server:
  port: 9998
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
spring:
  application:
    name: leishi-kernel-client
  datasource:
    url: jdbc:mysql://localhost:3306/leishi
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
mybatis:
  typeAliasesPackage: com.wxj.entity
  mapperLocations: classpath:mapper/*.xml
logging:
  level: com.wxj.dao: debug